---
- name: Install Vector | prepare architecture name when x64
  ansible.builtin.set_fact:
    architecture_name: amd64
  when: ansible_architecture == 'x86_64'
- name: Install Vector | prepare architecture name when else
  ansible.builtin.set_fact:
    architecture_name: undefined
  when: ansible_architecture != 'x86_64'
- name: Install Vector 
  become: true
  ansible.builtin.apt:
    deb: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    state: present