---
- name: Include tasks install CentOS
  ansible.builtin.include_tasks: install_yum.yml
  when: ansible_host == "centos"

- name: Include tasks install Ubuntu
  ansible.builtin.include_tasks: install_apt.yml
  when: ansible_host == "ubuntu"

- name: Vector | Create data dir
  become: true
  ansible.builtin.file:
    mode: "0755"
    path: "{{ vector_config_dir }}"
    state: "directory"
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: "templates/vector.yml.j2"
    dest: "{{ vector_config_dir }}/vector.yaml"
    mode: "0755"
- name: Vector | Register service
  become: true
  ansible.builtin.template:
    src: "templates/vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
    mode: "0755"
    backup: true