---
# handlers file for vector-role
- name: Start vector service
  become: true
  ansible.builtin.service:
    name: "vector"
    #pattern: "/usr/bin/vector"
    #state: started
    enabled: true
    state: restarted
  when: ansible_facts.virtualization_type != "docker"
...
